# Generated by Django 3.1.5 on 2021-02-07 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('dob', models.DateField()),
                ('blood_group', models.CharField(max_length=3)),
                ('contact', models.CharField(max_length=15)),
                ('county', models.CharField(max_length=20)),
                ('subscribe', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='LastDonDate',
            fields=[
                ('username', models.CharField(max_length=150)),
                ('date', models.DateField()),
                ('venue', models.CharField(max_length=254)),
                ('don_date_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
