# Generated by Django 3.1.5 on 2021-02-23 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='email',
        ),
        migrations.AddField(
            model_name='donor',
            name='username',
            field=models.CharField(default='Jacob', max_length=100, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
