# Generated by Django 3.1.5 on 2021-02-23 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0002_auto_20210223_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='email',
            field=models.EmailField(default='mabro@mailinator.com', max_length=254),
            preserve_default=False,
        ),
    ]
