# Generated by Django 3.1.5 on 2021-02-07 13:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloodDonated',
            fields=[
                ('donation_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('units_donated', models.IntegerField()),
                ('blood_group', models.CharField(max_length=5)),
                ('dc_id', models.CharField(max_length=15)),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='BloodRequest',
            fields=[
                ('request_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('units_required', models.IntegerField()),
                ('blood_group', models.CharField(max_length=5)),
                ('dc_id', models.CharField(max_length=15)),
                ('date', models.DateField(default=datetime.date.today)),
                ('display', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='BloodUsed',
            fields=[
                ('used_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('units_used', models.IntegerField()),
                ('blood_group', models.CharField(max_length=5)),
                ('dc_id', models.CharField(max_length=15)),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('event_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('dc_id', models.CharField(max_length=15)),
                ('poster', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('username', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('donation_center', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=15)),
                ('county', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=254)),
            ],
        ),
    ]
